import type { Candle } from "./marketData";
import type { Settings } from "@/context/SettingsContext";
import { analyzeQuantumFlow, type QFAResult, type QFASettings } from "./quantumFlow";

export function runAIAnalysis(
  candles: Candle[],
  settings: Settings,
  lang: "ar" | "en" = "ar",
): QFAResult {
  // Pass every customizable setting through to the engine.
  const qfaSettings: QFASettings = {
    swingLength: settings.swingLength,
    enableWall: settings.enableWall,
    enableWarZone: settings.enableWarZone,
    enableBOS: settings.enableBOS,
    enableFVG: settings.enableFVG,
    requireFvgConfluence: settings.requireFvgConfluence,
    allowCounterTrend: settings.allowCounterTrend,
    useGoldenZone: settings.useGoldenZone,
    requireGoldenZone: settings.requireGoldenZone,
    enableOrb: settings.enableOrb,
    engineMode: settings.engineMode,
    enableQFCross: settings.enableQFCross,
    useCustomRsiZones: settings.useCustomRsiZones,
    buyZoneLow: settings.buyZoneLow,
    buyZoneHigh: settings.buyZoneHigh,
    sellZoneLow: settings.sellZoneLow,
    sellZoneHigh: settings.sellZoneHigh,
    rsiPeriod: settings.rsiPeriod,
    emaRsiPeriod: settings.emaRsiPeriod,
    adxPeriod: settings.adxPeriod,
    atrPeriod: settings.atrPeriod,
    adxThreshold: settings.adxThreshold,
    spikeFilterMult: settings.spikeFilterMult,
    minVolatilityMult: settings.minVolatilityMult,
    useMtfFilter: settings.useMtfFilter,
    useVwapFilter: settings.useVwapFilter,
    useMacdDivFilter: settings.useMacdDivFilter,
    useDxyFilter: settings.useDxyFilter,
    useMoonFilter: settings.useMoonFilter,
    sessionFilter: settings.sessionFilter,
    weightBOS: settings.weightBOS,
    weightWall: settings.weightWall,
    weightGoldenZone: settings.weightGoldenZone,
    weightFVG: settings.weightFVG,
    weightMacdDiv: settings.weightMacdDiv,
    weightMtf: settings.weightMtf,
    weightVwap: settings.weightVwap,
    weightOrb: settings.weightOrb,
    weightMoon: settings.weightMoon,
    confluenceMode: settings.confluenceMode,
    minConfidence: settings.minConfidence,
    minRiskReward: settings.minRiskReward,
    enableEarlyWarning: settings.enableEarlyWarning,
    slMethod: settings.slMethod,
    tpMethod: settings.tpMethod,
    atrSlMult: settings.atrSlMult,
    atrTpMult: settings.atrTpMult,
    fibTp1: settings.fibTp1,
    fibTp2: settings.fibTp2,
    useTrailing: settings.useTrailing,
    signalStyle: settings.signalStyle,
  };
  return analyzeQuantumFlow(candles, qfaSettings, lang);
}
